# Enable stateless CSRF protection for forms and logins/logouts
#TODO: Review the settings when replacing custom CSRF with Symfony's
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
