# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
name: simbiat-dev

#It looks like subnet may change in some cases for no clear (to me) reason, so trying to force it
networks:
  #This network is used for the sake of isolation
  ofelia-internal:
    driver: bridge
  webserver:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
        - subnet: 2001:db8:1::/64

services:
  phpmyadmin:
    extends:
      file: ./build/docker/phpmyadmin/compose.yaml
      service: phpmyadmin

  geoip:
    extends:
      file: ./build/docker/geoip/compose.yaml
      service: geoip

  frankenphp:
    extends:
      file: ./build/docker/frankenphp/compose.yaml
      service: frankenphp

  crowdsec:
    extends:
      file: ./build/docker/crowdsec/compose.yaml
      service: crowdsec

  mariadb:
    extends:
      file: ./build/docker/mariadb/compose.yaml
      service: mariadb

  socket-proxy:
    extends:
      file: ./build/docker/socket-proxy/compose.yaml
      service: socket-proxy

  ofelia:
    extends:
      file: ./build/docker/ofelia/compose.yaml
      service: ofelia