# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  frankenphp:
    build:
      target: dev
    environment:
      APP_ENV: dev
    volumes:
      #PHPStorm's integrations require `/opt` to be persistent
      - ./data/temp:/opt:rw
      #Main project folder is RO but have to do RW on DEV due to https://github.com/docker/desktop-feedback/issues/491
      - ./:/app:rw
      #These 2 items need write permissions for Composer to run properly. They need to be uncommented once the above-mentioned bug is resolved
      #- ./composer.lock:/app/composer.lock:rw
      #- ./vendor:/app/vendor:rw
      #Name is used to ensure the .ini is loaded last
      - ./config/php_dev.ini:/usr/local/etc/php/conf.d/zz-dev-overrides.ini

  supercronic:
    environment:
      APP_ENV: dev
    volumes:
      - ./.env.dev:/etc/supercronic/.env.dev:ro

  bun:
    read_only: false
    volumes:
      - ./:/home/bun/app:rw
