name: simbiat-dev

#It looks like subnet may change in some cases for no clear reason, so trying to force it
networks:
  webserver:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
        - subnet: 2001:db8:1::/64

volumes:
  mariadb_data:
    driver: local
  mariadb_socket:
    driver: local
  geoip_data:
    driver: local
  crowdsec_data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

services:
  phpmyadmin:
    container_name: phpmyadmin
    build:
      context: ./build/docker/phpmyadmin
      dockerfile: Dockerfile
    profiles:
      - dev_only
    restart: no
    environment:
      APACHE_PORT: ${PHPMYADMIN_PORT}
      PMA_ARBITRARY: 0
      PMA_SOCKET: ${DATABASE_SOCKET}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: phpmyadmin
      PMA_CONTROLPASS: ${PHPMYADMIN_PASSWORD}
      PMA_UPLOADDIR: /etc/phpmyadmin/upload
      PMA_SAVEDIR: /etc/phpmyadmin/save
    networks:
      - webserver
    ports:
      - "127.0.0.1:${PHPMYADMIN_PORT}:${PHPMYADMIN_PORT}"
      - "[::1]:${PHPMYADMIN_PORT}:${PHPMYADMIN_PORT}"
    volumes:
      - mariadb_socket:/run/mysqld/:ro
      - ./build/phpmyadmin/upload:/etc/phpmyadmin/upload:ro
      - ./build/phpmyadmin/save:/etc/phpmyadmin/save:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb:mysql
      - mariadb:database
    #Before starting the container, it's better to clear the session files. It looks like otherwise the service can pick up older settings (unless manually clearing session data).
    #This is also important in case something happens to the phpMyAdmin database/tables, and they got removed, because otherwise it will keep showing error without allowing to fix it directly through the UI.
    command: >
      /bin/sh -c "rm -f -r /sessions/* &
                  /docker-entrypoint.sh apache2-foreground"

  #Attempt to use Bun from a container. Was meant to allow not keeping `node_modules` in the host, but it doesn't work
  #due to https://youtrack.jetbrains.com/issue/WEB-73725 and https://youtrack.jetbrains.com/issue/WEB-73722 bugs.
  #Bugs were originally raised for Node.js, but they are applicable to Bun, as well.
  #Also, possible that this is not even doable at all, and `node_modules` will need to be local either way.
  bun:
    container_name: bun
    image: oven/bun:latest
    profiles:
      - dev_only
    restart: no
    networks:
      - webserver
    volumes:
      #- ./:/home/bun/app:rw
      #- node_modules:/home/bun/app/node_modules/:rw
      #- ./bun.lock:/home/bun/app/bun.lock:rw
      #- ./package.json:/home/bun/app/package.json:rw
      - ./:/home/bun/app/:ro
    security_opt:
      - no-new-privileges=true
    #Command is required in case some manual runs are needed, since PHPStorm stops the container right away (uses "run")
    #command: tail -f /dev/null

  geoip:
    container_name: geoip
    build:
      context: ./build/docker/geoip
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GEOIPUPDATE_PRESERVE_FILE_TIMES: 1
      GEOIPUPDATE_FREQUENCY: 24
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIP_ACCOUNT}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIP_LICENSE}
      GEOIPUPDATE_EDITION_IDS: GeoLite2-ASN GeoLite2-City
    volumes:
      - geoip_data:/usr/share/GeoIP/:rw
    security_opt:
      - no-new-privileges=true

  frankenphp:
    container_name: frankenphp
    build:
      context: ./build/docker/frankenphp
      dockerfile: Dockerfile
      args:
        WEB_SERVER_TEST: ${WEB_SERVER_TEST}
    restart: unless-stopped
    environment:
      WEB_SERVER_TEST: ${WEB_SERVER_TEST}
      CROWDSEC_API_KEY: ${CROWDSEC_CADDY_KEY}
      PHP_CS_FIXER_FUTURE_MODE: 1
    networks:
      - webserver
    ports:
      - "80:80" # HTTP
      - "443:443/tcp" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      #RO for MariaDB socket
      - mariadb_socket:/run/mysqld/:ro
      #geoip mapping
      - geoip_data:/geoip:ro
      #Caddy folders requiring RW
      - caddy_data:/data:rw
      - caddy_config:/config:rw
      #Main project folder is RO
      - ./:/app:ro
      #Some files/folders are overridden for RW permissions
      - ./composer.lock:/app/composer.lock:rw
      - ./build/DDL:/app/build/DDL:rw
      - ./data:/app/data:rw
      - ./public/assets/images/fftracker/icons:/app/public/assets/images/fftracker/icons:rw
      - ./public/assets/images/fftracker/crests-components:/app/public/assets/images/fftracker/crests-components:rw
      - ./logs:/app/logs:rw
      - ./vendor:/app/vendor:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      geoip:
        condition: service_started
      crowdsec:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    links:
      - mariadb:mysql
      - mariadb:database
    command: >
      /bin/sh -c "printenv | grep -v "no_proxy" > /etc/environment &&
                  #We need to start cron service before the endpoint
                  cron &&
                  docker-php-entrypoint --config /usr/local/etc/php/caddy.json5 --adapter json5"

  crowdsec:
    #Based on https://github.com/crowdsecurity/example-docker-compose/tree/main/caddy
    container_name: crowdsec
    build:
      context: ./build/docker/crowdsec
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GID: 1000
      COLLECTIONS: crowdsecurity/caddy
        crowdsecurity/whitelist-good-actors
        crowdsecurity/http-cve
        crowdsecurity/http-dos
        crowdsecurity/base-http-scenarios
        crowdsecurity/http-extended-context
        crowdsecurity/appsec-generic-rules
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/appsec-wordpress
        crowdsecurity/wordpress
        crowdsecurity/discord-crawler-whitelist
        crowdsecurity/appsec-crs
        crowdsecurity/appsec-crs-inband
        crowdsecurity/linux
        crowdsecurity/linux-lpe
        crowdsecurity/iptables
        crowdsecurity/mariadb
        crowdsecurity/sshd
        barnoux/caddy-coraza
        openappsec/openappsec
      BOUNCER_KEY_CADDY: ${CROWDSEC_CADDY_KEY}
      BOUNCER_KEY_IPTABLES: ${CROWDSEC_IPTABLES_KEY}
      ENROLL_KEY: ${CROWDSEC_ENROLL_KEY}
      ENABLE_CONSOLE_MANAGEMENT: true
      ENABLE_CONSOLE_ALL: true
      DATABASE_SOCKET: ${DATABASE_SOCKET}
      DATABASE_PASSWORD: ${CROWDSEC_PASSWORD}
    networks:
      - webserver
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:6060:6060"
      - "127.0.0.1:7422:7422"
      #These are valid despite the IDE highlighting them. https://youtrack.jetbrains.com/issue/IJPL-228615
      - "[::1]:8080:8080"
      - "[::1]:6060:6060"
      - "[::1]:7422:7422"
    volumes:
      #RO for MariaDB socket
      - mariadb_socket:/run/mysqld/:ro
      #Data folder is required to be mounted, otherwise container does not start
      - crowdsec_data:/var/lib/crowdsec/data/:rw
      #RO for GeoLite2 files
      - geoip_data:/geoip:ro
      #Required to read syslog. This will be valid only on UNIX
      - /var/log/:/var/log/:ro
      #Caddy logs folder is RW, because we're also writing Crowdsec logs here
      - ./logs:/usr/local/logs/:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      geoip:
        condition: service_started
      mariadb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "cscli", "lapi", "status" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 3
    #Override image's entrypoint to execute custom command
    entrypoint: ''
    command: >
      /bin/sh -c "#Need to link GeoIP files
                  ln -sf /geoip/GeoLite2-ASN.mmdb /var/lib/crowdsec/data/GeoLite2-ASN.mmdb &&
                  ln -sf /geoip/GeoLite2-City.mmdb /var/lib/crowdsec/data/GeoLite2-City.mmdb &&
                  #Need to ensure that CRS files are up-to-date every time, so we remove them first
                  rm -f /var/lib/crowdsec/data/REQUEST-9*.conf /var/lib/crowdsec/data/RESPONSE-9*.conf /var/lib/crowdsec/data/iis-errors.data /var/lib/crowdsec/data/java-classes.data /var/lib/crowdsec/data/java-errors.data /var/lib/crowdsec/data/lfi-os-files.data /var/lib/crowdsec/data/php-config-directives.data /var/lib/crowdsec/data/php-errors.data /var/lib/crowdsec/data/php-errors-pl2.data /var/lib/crowdsec/data/php-function-names-933150.data /var/lib/crowdsec/data/php-function-names-933151.data /var/lib/crowdsec/data/php-variables.data /var/lib/crowdsec/data/restricted-files.data /var/lib/crowdsec/data/restricted-upload.data /var/lib/crowdsec/data/scanners-user-agents.data /var/lib/crowdsec/data/sql-errors.data /var/lib/crowdsec/data/ssrf.data /var/lib/crowdsec/data/unix-shell.data /var/lib/crowdsec/data/web-shells-asp.data /var/lib/crowdsec/data/web-shells-php.data /var/lib/crowdsec/data/windows-powershell-commands.data &
                  cp -r /var/lib/OWASP/rules/* /var/lib/crowdsec/data/ &&
                  mkdir -p /var/lib/crowdsec/data/CoreRuleSet/ &&
                  cp -r /etc/crowdsec/CoreRuleSet/* /var/lib/crowdsec/data/CoreRuleSet/ &&
                  #Don't remember why this is required, I think the folder is not created automatically in some cases
                  mkdir -p /etc/periodic/daily/ &
                  /bin/bash /docker_start.sh"

  mariadb:
    container_name: mariadb
    build:
      context: ./build/docker/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WEB_SERVER_TEST: ${WEB_SERVER_TEST}
      MARIADB_AUTO_UPGRADE: true
      #Password for backups created by CRON job
      MARIADB_BACKUP_PASSWORD: ${MARIADB_BACKUP_PASSWORD}
      #Limit root access from localhost only
      MARIADB_ROOT_HOST: localhost
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_MYSQL_LOCALHOST_USER: true
      #Pass database name for backup
      DATABASE_NAME: ${DATABASE_NAME}
    networks:
      - webserver
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      #RW for the socket
      - mariadb_socket:/run/mysqld/:rw
      #RW for database files directory
      - mariadb_data:/var/lib/mysql:rw
      #RW for logs directory
      - ./logs:/usr/local/logs:rw
      #RW for backups directory
      - ${MARIADB_BACKUP_DIR}:/usr/local/backups:rw
      #RO for DDL directory, used during maintenance stuff
      - ./build/DDL:/usr/local/DDL:ro
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--defaults-file=/etc/mysql/conf.d/my.cnf", "--connect", "--innodb_initialized", "--innodb_buffer_pool_loaded", "--mariadbupgrade" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 3
    command: >
      /bin/sh -c "printenv | grep -v "no_proxy" > /etc/environment &&
                  #We need to ensure that buffer pool file exists
                  touch /var/lib/mysql/ib_buffer_pool &&
                  chown mysql:mysql /var/lib/mysql/ib_buffer_pool &&
                  #We need to start cron service before the endpoint
                  cron &&
                  #If maintenance flag is found, it implies crash during maintenance: rename it to indicate this
                  mv /usr/local/logs/db_maintenance.flag /usr/local/logs/backup_crash.flag
                  docker-entrypoint.sh mariadbd-safe"
