name: simbiat-dev

# Looks like subnet may change in some cases for no apparent reason, so trying to force it
networks:
  webserver:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.21.0.0/16
        - subnet: 2001:db8:1::/64

volumes:
  mariadb_socket:
    driver: local

services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2.2-apache
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: 0
      PMA_SOCKET: ${DATABASE_SOCKET}
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      PMA_PMADB: phpmyadmin
      PMA_CONTROLUSER: phpmyadmin
      PMA_CONTROLPASS: ${PHPMYADMIN_PASSWORD}
      PMA_UPLOADDIR: /etc/phpmyadmin/upload
      PMA_SAVEDIR: /etc/phpmyadmin/save
    networks:
      - webserver
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - mariadb_socket:/run/mysqld/:ro
      - ./config/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./build/phpmyadmin/upload:/etc/phpmyadmin/upload:ro
      - ./build/phpmyadmin/save:/etc/phpmyadmin/save:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      local.simbiat.dev:
        condition: service_healthy
    links:
      - local.simbiat.dev:mysql
      - local.simbiat.dev:database

  geoip:
    container_name: geoip
    build:
      context: ./config/geoip
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GEOIPUPDATE_PRESERVE_FILE_TIMES: 1
      GEOIPUPDATE_FREQUENCY: 24
      GEOIPUPDATE_ACCOUNT_ID: ${GEOIP_ACCOUNT}
      GEOIPUPDATE_LICENSE_KEY: ${GEOIP_LICENSE}
      GEOIPUPDATE_EDITION_IDS: GeoLite2-ASN GeoLite2-City
    volumes:
      - ./data/geoip/:/usr/share/GeoIP/:rw

  frankenphp:
    container_name: frankenphp
    build:
      context: ./config/frankenphp
      dockerfile: Dockerfile
      args:
        WEB_SERVER_TEST: ${WEB_SERVER_TEST}
    restart: unless-stopped
    environment:
      WEB_SERVER_TEST: ${WEB_SERVER_TEST}
      CROWDSEC_API_KEY: ${CROWDSEC_CADDY_KEY}
      PHP_INI_DIR: /usr/local/php/config
      PHP_INI_SCAN_DIR: /usr/local/php/config
    networks:
      - webserver
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - mariadb_socket:/run/mysqld/:ro
      - ./:/app:rw
      - ./config/frankenphp:/usr/local/php/config:rw
      - ${CADDY_DATA_DIR}:/data:rw
      - ./data/caddy_config:/config:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      geoip:
        condition: service_started
      crowdsec:
        condition: service_healthy
      local.simbiat.dev:
        condition: service_healthy
    links:
      - local.simbiat.dev:mysql
      - local.simbiat.dev:database
    #We need to register cron task and start cron service before the endpoint
    command: >
      /bin/sh -c "printenv | grep -v "no_proxy" > /etc/environment &&
                  cp /usr/local/php/config/cron/php.cron /etc/cron.d/php.cron &&
                  chmod 0644 /etc/cron.d/php.cron &&
                  crontab /etc/cron.d/php.cron &&
                  cron &&
                  docker-php-entrypoint --config /usr/local/php/config/caddy.json5 --adapter json5"

  crowdsec:
    #Based on https://github.com/crowdsecurity/example-docker-compose/tree/main/caddy
    container_name: crowdsec
    build:
      context: ./config/crowdsec
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      GID: 1000
      COLLECTIONS: crowdsecurity/caddy crowdsecurity/whitelist-good-actors crowdsecurity/http-cve crowdsecurity/http-dos crowdsecurity/base-http-scenarios crowdsecurity/appsec-crs crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-wordpress crowdsecurity/wordpress crowdsecurity/discord-crawler-whitelist openappsec/openappsec
      BOUNCER_KEY_CADDY: ${CROWDSEC_CADDY_KEY}
      BOUNCER_KEY_IPTABLES: ${CROWDSEC_IPTABLES_KEY}
      ENROLL_KEY: ${CROWDSEC_ENROLL_KEY}
      ENABLE_CONSOLE_MANAGEMENT: true
      ENABLE_CONSOLE_ALL: true
      DATABASE_SOCKET: ${DATABASE_SOCKET}
      DATABASE_PASSWORD: ${CROWDSEC_PASSWORD}
    networks:
      - webserver
    ports:
      - "8080:8080"
      - "6060:6060"
      - "7422:7422"
    volumes:
      - mariadb_socket:/run/mysqld/:ro
      - ./data/crowdsec/:/var/lib/crowdsec/data/:rw
      - ./data/geoip/GeoLite2-ASN.mmdb:/var/lib/crowdsec/data/GeoLite2-ASN.mmdb:ro
      - ./data/geoip/GeoLite2-City.mmdb:/var/lib/crowdsec/data/GeoLite2-City.mmdb:ro
      - ./config/crowdsec/yaml/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./config/crowdsec/yaml/acquis/:/etc/crowdsec/acquis.d/:rw
      - ./config/crowdsec/yaml/config.yaml.local:/etc/crowdsec/config.yaml.local:ro
      - ./config/crowdsec/yaml/online_api_credentials.yaml:/etc/crowdsec/online_api_credentials.yaml:ro
      - ./config/crowdsec/yaml/appsec/simbiat-appsec.yaml:/etc/crowdsec/appsec-configs/simbiat-appsec.yaml:ro
      - ./config/crowdsec/yaml/appsec/simbiat-seclang.yaml:/etc/crowdsec/appsec-rules/simbiat-seclang.yaml:ro
      - ./config/crowdsec/01-coraza-recommended.conf:/var/lib/crowdsec/data/01-coraza-recommended.conf:ro
      - ./config/crowdsec/02-crs-setup.conf:/var/lib/crowdsec/data/02-crs-setup.conf:ro
      - ./config/crowdsec/03-custom-blocks.conf:/var/lib/crowdsec/data/03-custom-blocks.conf:ro
      - ./config/crowdsec/04-exclusions-before-crs.conf:/var/lib/crowdsec/data/04-exclusions-before-crs.conf:ro
      - ./config/crowdsec/05-exclusions-after-crs.conf:/var/lib/crowdsec/data/05-exclusions-after-crs.conf:ro
      #Required to read syslog. This will be valid only on UNIX
      - /var/log/:/var/log/:ro
      #Caddy logs folder is RW, because we're also writing Crowdsec logs here
      - ./logs:/usr/local/logs/:rw
    security_opt:
      - no-new-privileges=true
    depends_on:
      geoip:
        condition: service_started
      local.simbiat.dev:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "cscli", "lapi", "status" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 3
    #Override image's entrypoint to execute custom command
    entrypoint: ''
    #We clone latest configs from coreruleset, since those packed with CrowdSec are very old. We also want to remove .git files due to https://youtrack.jetbrains.com/issue/WI-80162/Auto-adds-a-git-repo-from-ignored-directory which just annoys me
    command: >
      /bin/sh -c "rm -r -f /var/lib/crowdsec/data/coreruleset &&
                  mkdir -p /var/lib/crowdsec/data/coreruleset &&
                  git clone https://github.com/coreruleset/coreruleset /var/lib/crowdsec/data/coreruleset --branch v4.12.0 &&
                  rm -r -f /var/lib/crowdsec/data/coreruleset/.git* &&
                  mkdir -p /etc/periodic/daily/ &&
                  /bin/bash /docker_start.sh"

  local.simbiat.dev:
    container_name: mariadb
    build:
      context: ./config/mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      WEB_SERVER_TEST: ${WEB_SERVER_TEST}
      MARIADB_AUTO_UPGRADE: true
      #Password for backups created by CRON job
      MARIADB_BACKUP_PASSWORD: ${MARIADB_BACKUP_PASSWORD}
    networks:
      - webserver
    volumes:
      - mariadb_socket:/run/mysqld/:rw
      - ${MARIADB_DATA_DIR}:/var/lib/mysql:rw
      - ./config/mysql:/etc/mysql/conf.d:ro
      - ./logs:/usr/local/logs:rw
      - ${MARIADB_BACKUP_DIR}:/usr/local/backups:rw
      - ./build/DDL:/usr/local/DDL:ro
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--defaults-file=/etc/mysql/conf.d/my.cnf", "--connect", "--innodb_initialized", "--innodb_buffer_pool_loaded", "--mariadbupgrade" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 3
    #We want to generate keys automatically, and it is also a good idea to regenerate them on each restart
    #We need to ensure that buffer pool file exists, too
    #We need to register cron tasks and start cron service before the endpoint
    command: >
      /bin/sh -c "printenv | grep -v "no_proxy" > /etc/environment &&
                  touch /var/lib/mysql/ib_buffer_pool &&
                  chown mysql:mysql /var/lib/mysql/ib_buffer_pool &&
                  cp /etc/mysql/conf.d/cron/mariadb.cron /etc/cron.d/mariadb.cron &&
                  chmod 0644 /etc/cron.d/mariadb.cron &&
                  crontab /etc/cron.d/mariadb.cron &&
                  cron &&
                  docker-entrypoint.sh mariadbd"
