/**
 * @file ESLint config.
 */
// eslint-disable-next-line github/filenames-match-regex
import stylistic from '@stylistic/eslint-plugin';
import globals from 'globals';
import eslint from '@eslint/js';
import ts_eslint from 'typescript-eslint';
import ts_parser from '@typescript-eslint/parser';
import compat from 'eslint-plugin-compat';
import { defineConfig, globalIgnores } from 'eslint/config';
import { configs as deMorgan } from 'eslint-plugin-de-morgan';
import { plugin as ex } from 'eslint-plugin-exception-handling';
import no_unsanitized from 'eslint-plugin-no-unsanitized';
import markdown from '@eslint/markdown';
import json from '@eslint/json';
import no_constructor from 'eslint-plugin-no-constructor-bind';
import redos from 'eslint-plugin-redos';
import pii from 'eslint-plugin-pii';
import xss from 'eslint-plugin-xss';
import github from 'eslint-plugin-github';
import plugin_promise from 'eslint-plugin-promise';
import { configs as regexp_plugin } from 'eslint-plugin-regexp';
import { configs as sonarjs } from 'eslint-plugin-sonarjs';
import unicorn from 'eslint-plugin-unicorn';
import jsdoc from 'eslint-plugin-jsdoc';
import simbiat from '@simbiat/eslint-plugin-simbiat';
import { configs as security } from 'eslint-plugin-security';

// It looks like a false positive for the inspection, so suppressing it.
// noinspection JSCheckFunctionSignatures
export default defineConfig([
  globalIgnores([
    './build/js/dev/types/*',
    './build/js/dev/ESLintPlugin/dist/*',
    './build/js/dev/StylelintPlugin/dist/*',
  ]),
  {
    files: ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.mjs', '**/*.mjsx', '**/*.mts', '**/*.mtsx'],
    extends: [
      compat.configs['flat/recommended'],
      eslint.configs.recommended,
      stylistic.configs.recommended,
      deMorgan.recommended,
      // GitHub configs include eslint-plugin-escompat, eslint-plugin-import, eslint-plugin-jsx-a11y, eslint-plugin-prettier, eslint-plugin-eslint-comments, eslint-plugin-filenames, eslint-plugin-i18n-text, eslint-plugin-no-only-tests
      github.getFlatConfigs().browser,
      github.getFlatConfigs().recommended,
      github.getFlatConfigs().react,
      plugin_promise.configs['flat/recommended'],
      regexp_plugin['flat/recommended'],
      sonarjs.recommended,
      security.recommended,
      jsdoc.configs['flat/recommended'],
      jsdoc.configs['flat/recommended-mixed'],
    ],
    plugins: {
      '@stylistic': stylistic,
      'ex': ex,
      'no-unsanitized': no_unsanitized,
      'no-constructor-bind': no_constructor,
      'redos': redos,
      'pii': pii,
      'xss': xss,
      'promise': plugin_promise,
      'unicorn': unicorn,
      'simbiat': simbiat,
      'jsdoc': jsdoc,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.worker,
      },
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      'camelcase': 'off',
      'compat/compat': 'error',
      'array-callback-return': ['error', {
        checkForEach: true,
      }],
      'no-await-in-loop': 'warn',
      'no-constructor-return': 'warn',
      'no-promise-executor-return': 'warn',
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': 'error',
      'require-atomic-updates': 'error',
      'accessor-pairs': ['error', {
        getWithoutSet: true,
      }],
      'arrow-body-style': ['warn', 'always'],
      'max-depth': 'off',
      'max-params': ['warn', 5],
      'consistent-return': 'error',
      'curly': 'warn',
      'default-case': 'error',
      'default-case-last': 'error',
      'eqeqeq': 'error',
      'func-names': ['error', 'always'],
      'func-style': ['error', 'declaration'],
      'grouped-accessor-pairs': ['error', 'getBeforeSet'],
      'no-bitwise': 'error',
      'no-caller': 'error',
      '@stylistic/no-confusing-arrow': 'warn',
      'no-console': ['warn', { allow: [''] }],
      'no-else-return': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-implicit-coercion': 'error',
      'no-inline-comments': 'off',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'warn',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-new-func': 'error',
      'no-object-constructor': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-return-assign': 'error',
      'no-script-url': 'error',
      'no-sequences': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'error',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'warn',
      'no-useless-rename': 'warn',
      'no-var': 'error',
      'object-shorthand': 'error',
      'one-var': ['error', 'never'],
      '@stylistic/one-var-declaration-per-line': ['warn', 'always'],
      '@stylistic/eol-last': 'warn',
      'operator-assignment': ['error', 'always'],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'warn',
      'prefer-exponentiation-operator': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'warn',
      'radix': 'error',
      'require-unicode-regexp': 'error',
      'symbol-description': 'error',
      'yoda': 'error',
      '@stylistic/array-bracket-newline': ['warn', 'consistent'],
      '@stylistic/array-element-newline': 'off',
      '@stylistic/function-call-argument-newline': ['warn', 'consistent'],
      '@stylistic/no-multi-spaces': 'warn',
      '@stylistic/object-property-newline': 'warn',
      '@stylistic/semi-style': ['warn', 'last'],
      '@stylistic/comma-dangle': 'warn',
      '@stylistic/quotes': 'warn',
      '@stylistic/object-curly-spacing': 'warn',
      '@stylistic/padded-blocks': 'warn',
      '@stylistic/arrow-parens': 'warn',
      // Conflicts with PHPStorm settings
      '@stylistic/indent': 'off',
      '@stylistic/quote-props': 'warn',
      '@stylistic/switch-colon-spacing': ['warn', {
        after: true,
        before: false,
      }],
      '@stylistic/wrap-regex': 'warn',
      '@stylistic/no-multiple-empty-lines': 'warn',
      '@stylistic/brace-style': ['warn', '1tbs'],
      '@stylistic/no-trailing-spaces': 'warn',
      '@stylistic/space-infix-ops': 'warn',
      '@stylistic/comma-spacing': 'warn',
      '@stylistic/block-spacing': 'warn',
      '@stylistic/key-spacing': 'warn',
      'block-scoped-var': 'error',
      'consistent-this': ['error', 'me'],
      'guard-for-in': 'error',
      'logical-assignment-operators': ['error', 'always'],
      'no-div-regex': 'error',
      'no-implicit-globals': 'error',
      'no-negated-condition': 'error',
      'no-new': 'error',
      'no-nested-ternary': 'error',
      //Covered by IDE
      'no-param-reassign': 'off',
      'no-useless-return': 'error',
      'prefer-named-capture-group': 'warn',
      'vars-on-top': 'error',
      '@stylistic/function-paren-newline': ['warn', 'multiline'],
      '@stylistic/newline-per-chained-call': 'warn',
      '@stylistic/spaced-comment': 'off',
      '@stylistic/indent-binary-ops': 'warn',
      'no-void': ['warn', { allowAsStatement: true }],
      'default-param-last': 'error',
      'no-invalid-this': 'error',
      'no-loop-func': 'error',
      'no-shadow': 'error',
      'no-unused-expressions': 'error',
      'no-use-before-define': 'error',
      'no-array-constructor': 'error',
      'no-empty-function': 'error',
      '@stylistic/no-extra-semi': 'warn',
      '@stylistic/member-delimiter-style': 'warn',
      '@stylistic/semi': ['warn', 'always'],
      '@stylistic/operator-linebreak': 'warn',
      'no-implied-eval': 'error',
      'require-await': 'error',
      'dot-notation': 'error',
      'no-throw-literal': 'error',
      'no-useless-constructor': 'error',
      'no-constructor-bind/no-constructor-bind': 'error',
      'no-constructor-bind/no-constructor-state': 'error',
      'no-unused-vars': 'warn',
      'redos/no-vulnerable': 'error',
      'no-unsanitized/method': 'error',
      'no-unsanitized/property': 'error',
      'pii/no-email': 'error',
      'pii/no-ip': 'error',
      'pii/no-phone-number': 'error',
      'xss/no-location-href-assign': 'error',
      'promise/no-multiple-resolved': 'error',
      'promise/prefer-await-to-callbacks': 'warn',
      'promise/prefer-await-to-then': 'warn',
      'promise/prefer-catch': 'error',
      'promise/spec-only': 'error',
      // Too many false positives highlighting `if` statements inside `then` when there is no return expected as result of the `if`
      'promise/always-return': 'off',
      'regexp/no-octal': 'error',
      'regexp/no-standalone-backslash': 'error',
      'regexp/prefer-escape-replacement-dollar-char': 'error',
      'regexp/require-unicode-regexp': 'error',
      'regexp/require-unicode-sets-regexp': 'warn',
      'regexp/hexadecimal-escape': 'warn',
      'regexp/letter-case': 'warn',
      'regexp/prefer-lookaround': 'warn',
      'regexp/prefer-named-backreference': 'warn',
      'regexp/prefer-named-capture-group': 'warn',
      'regexp/prefer-named-replacement': 'warn',
      'regexp/prefer-result-array-groups': 'warn',
      'regexp/sort-character-class-elements': 'warn',
      'regexp/unicode-escape': 'error',
      'regexp/unicode-property': 'warn',
      'regexp/grapheme-string-literal': 'warn',
      'regexp/sort-flags': 'warn',
      'sonarjs/arguments-usage': 'error',
      // conflicts with Stylelint rule
      'sonarjs/arrow-function-convention': 'off',
      'sonarjs/aws-iam-all-resources-accessible': 'error',
      'sonarjs/bool-param-default': 'error',
      'sonarjs/class-prototype': 'error',
      'sonarjs/destructuring-assignment-syntax': 'error',
      'sonarjs/file-name-differ-from-class': 'error',
      // not sure if this helps that much, probably would end up excluding cases
      'sonarjs/nested-control-flow': 'off',
      'sonarjs/no-built-in-override': 'error',
      'sonarjs/no-collapsible-if': 'warn',
      // gets triggered by CSS queries, which probably should not be put into a variable
      'sonarjs/no-duplicate-string': 'off',
      'sonarjs/no-for-in-iterable': 'error',
      'sonarjs/no-function-declaration-in-block': 'error',
      'sonarjs/no-implicit-dependencies': 'error',
      'sonarjs/no-inconsistent-returns': 'error',
      'sonarjs/no-incorrect-string-concat': 'error',
      'sonarjs/no-nested-incdec': 'error',
      'sonarjs/no-nested-switch': 'error',
      // no-reference-error returns too many false positives for some reason
      'sonarjs/no-reference-error': 'off',
      // argument-type returns too many false positives for some reason
      'sonarjs/argument-type': 'off',
      'sonarjs/no-require-or-define': 'error',
      'sonarjs/no-return-type-any': 'error',
      'sonarjs/no-undefined-assignment': 'error',
      'sonarjs/no-unused-function-argument': 'error',
      'sonarjs/no-variable-usage-before-declaration': 'error',
      'sonarjs/no-wildcard-import': 'error',
      'sonarjs/non-number-in-arithmetic-expression': 'error',
      'sonarjs/operation-returning-nan': 'error',
      'sonarjs/prefer-immediate-return': 'error',
      'sonarjs/prefer-object-literal': 'error',
      'sonarjs/strings-comparison': 'error',
      'sonarjs/unicode-aware-regex': 'error',
      'sonarjs/no-unused-vars': 'warn',
      'sonarjs/no-dead-store': 'warn',
      'sonarjs/values-not-convertible-to-numbers': 'error',
      'sonarjs/unused-import': 'warn',
      // This one highlights legitimate use of void expression. Potentially problematic ones are highlighted by other rules.
      'sonarjs/void-use': 'off',
      'sonarjs/function-name': ['warn', {
        format: '^[_a-z][a-zA-Z0-9]+$',
      }],
      'sonarjs/class-name': ['warn', {
        format: '^[A-Z][a-zA-Z]*$',
      }],
      // There are other inspections that do something similar already, and I am not even sure about their usefulness, let alone this one.
      'sonarjs/cognitive-complexity': 'off',
      // Seems to require use of 1 return statement in some functions that can return different types at different branches. This requires restructuring of functions
      // that can prevent early returns. See little benefit in this.
      'sonarjs/function-return-type': 'off',
      'github/filenames-match-regex': ['warn', '^[A-Z][a-zA-Z0-9_]*$'],
      'github/no-blur': 'warn',
      'github/array-foreach': 'warn',
      'github/no-then': 'warn',
      'github/get-attribute': 'warn',
      'escompat/no-optional-catch': 'off',
      'escompat/no-optional-chaining': 'off',
      'i18n-text/no-en': 'off',
      // Comes from GitHub, but Stylistic duplicates all the rules, and they seem a bit more readable to me
      'prettier/prettier': 'off',
      // From GitHub, seems to cause noise
      'eslint-comments/no-use': 'off',
      // Conflicts with PHPStorm rules
      'import/no-unresolved': 'off',
      'import/extensions': 'off',
      'unicorn/prefer-query-selector': 'warn',
      'jsdoc/check-indentation': 'warn',
      'jsdoc/check-line-alignment': 'warn',
      'jsdoc/check-syntax': 'warn',
      'jsdoc/check-template-names': 'warn',
      'jsdoc/convert-to-jsdoc-comments': 'warn',
      'jsdoc/imports-as-dependencies': 'warn',
      'jsdoc/no-bad-blocks': 'warn',
      'jsdoc/no-blank-block-descriptions': 'warn',
      'jsdoc/no-blank-blocks': 'warn',
      'jsdoc/prefer-import-tag': 'warn',
      'jsdoc/require-asterisk-prefix': 'warn',
      'jsdoc/require-description': 'warn',
      'jsdoc/require-description-complete-sentence': 'warn',
      'jsdoc/require-file-overview': 'warn',
      'jsdoc/require-hyphen-before-param-description': 'warn',
      'jsdoc/require-next-description': 'warn',
      'jsdoc/require-template': 'warn',
      'jsdoc/require-template-description': 'warn',
      'jsdoc/require-throws': 'warn',
      'jsdoc/require-yields-description': 'warn',
      'jsdoc/sort-tags': 'warn',
      'jsdoc/ts-method-signature-style': ['warn', 'property'],
      'jsdoc/ts-no-unnecessary-template-expression': 'warn',
      'jsdoc/ts-prefer-function-type': 'warn',
      'jsdoc/type-formatting': 'warn',
      'jsdoc/require-returns': 'off',
      'jsdoc/require-returns-description': 'off',
      'jsdoc/require-param': ['warn', {
        interfaceExemptsParamsCheck: true,
      }],
      'jsdoc/require-jsdoc': ['warn', {
        exemptEmptyConstructors: true,
        require: {
          ArrowFunctionExpression: true,
          ClassDeclaration: true,
          ClassExpression: true,
          FunctionDeclaration: true,
          FunctionExpression: true,
          MethodDefinition: true,
        },
      }],
      'simbiat/no-forbidden-in-constructor': 'error',
      'simbiat/no-external-listeners-in-constructor': 'warn',
      'simbiat/prefer-field-initializer': 'warn',
      'simbiat/require-super-first-in-constructor': 'error',
      'simbiat/require-listener-cleanup': 'warn',
      'simbiat/no-keypress-event': 'error',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.mtsx'],
    extends: [
      ts_eslint.configs.recommendedTypeChecked,
      ts_eslint.configs.stylisticTypeChecked,
      ts_eslint.configs.strict,
    ],
    languageOptions: {
      parser: ts_parser,
      parserOptions: {
        sourceType: 'module',
        projectService: true,
      },
    },
    rules: {
      '@typescript-eslint/explicit-function-return-type': 'error',
      '@typescript-eslint/explicit-member-accessibility': 'error',
      '@typescript-eslint/explicit-module-boundary-types': 'error',
      '@typescript-eslint/method-signature-style': ['error', 'property'],
      '@typescript-eslint/no-unnecessary-qualifier': 'error',
      '@typescript-eslint/no-useless-empty-export': 'error',
      '@typescript-eslint/prefer-readonly': 'warn',
      '@typescript-eslint/promise-function-async': 'error',
      '@typescript-eslint/require-array-sort-compare': 'error',
      '@typescript-eslint/sort-type-constituents': 'warn',
      '@typescript-eslint/strict-boolean-expressions': ['error'],
      '@typescript-eslint/switch-exhaustiveness-check': ['error', {
        allowDefaultCaseForExhaustiveSwitch: true,
        considerDefaultExhaustiveForUnions: true,
        requireDefaultForNonUnion: true,
      }],
      'no-useless-constructor': 'off',
      '@typescript-eslint/no-useless-constructor': 'warn',
      '@typescript-eslint/consistent-type-exports': 'warn',
      '@typescript-eslint/consistent-type-imports': 'warn',
      '@typescript-eslint/prefer-enum-initializers': 'error',
      '@typescript-eslint/no-confusing-void-expression': 'error',
      'default-param-last': 'off',
      '@typescript-eslint/default-param-last': 'error',
      'no-dupe-class-members': 'off',
      '@typescript-eslint/no-dupe-class-members': 'error',
      'no-invalid-this': 'off',
      '@typescript-eslint/no-invalid-this': 'error',
      'no-loop-func': 'off',
      '@typescript-eslint/no-loop-func': 'error',
      'no-shadow': 'off',
      '@typescript-eslint/no-shadow': 'error',
      'no-use-before-define': 'off',
      '@typescript-eslint/no-use-before-define': 'error',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/prefer-optional-chain': 'warn',
      // Rule from GitHub that needs an override.
      '@typescript-eslint/array-type': ['error', { default: 'array-simple' }],
      // Using some static classes to isolate functions, since all modules are bundled into 1 file, which makes all functions available globally
      '@typescript-eslint/no-extraneous-class': ['warn',
        {
          allowConstructorOnly: false,
          allowEmpty: false,
          allowStaticOnly: true,
          allowWithDecorator: false,
        }],
      // Looks like need to duplicate this because it gets overridden by some extension
      'prefer-const': 'warn',
      'ex/no-unhandled': 'error',
      'ex/might-throw': 'warn',
      'ex/use-error-cause': 'error',
      'jsdoc/no-types': 'warn',
      'simbiat/require-type-parameter': 'warn',
    },
  },
  {
    files: ['**/*.md', '**/*.markdown'],
    plugins: { markdown },
    extends: ['markdown/recommended'],
    rules: {
      'markdown/no-bare-urls': 'warn',
      'markdown/no-duplicate-headings': 'error',
    },
  },
  {
    files: ['** /*.json', '** /*.jsonc', '.vscode/*.json', '** /*.json5'],
    ignores: ['package-lock.json'],
    language: 'json/json',
    ...json.configs.recommended,
  },
  {
    files: ['** /*.jsonc', '.vscode/*.json'],
    language: 'json/jsonc',
  },
  {
    files: ['** /*.json5'],
    language: 'json/json5',
  },
]);
