name: simbiat/simbiat-seclang
description: "Rules based on Coraza recommendations with some customizations"
seclang_files_rules:
  - /CoreRuleSet/01-coraza-recommended.conf
  - /CoreRuleSet/02-crs-setup.conf
  - /CoreRuleSet/03-custom-blocks.conf
  - /CoreRuleSet/04-exclusions-before-crs.conf
  - REQUEST-901-INITIALIZATION.conf
  - REQUEST-905-COMMON-EXCEPTIONS.conf
  - REQUEST-911-METHOD-ENFORCEMENT.conf
  - REQUEST-913-SCANNER-DETECTION.conf
  - REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  - REQUEST-921-PROTOCOL-ATTACK.conf
  - REQUEST-922-MULTIPART-ATTACK.conf
  - REQUEST-930-APPLICATION-ATTACK-LFI.conf
  - REQUEST-931-APPLICATION-ATTACK-RFI.conf
  - REQUEST-932-APPLICATION-ATTACK-RCE.conf
  - REQUEST-933-APPLICATION-ATTACK-PHP.conf
  - REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  - REQUEST-941-APPLICATION-ATTACK-XSS.conf
  - REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  - REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  - REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  - REQUEST-949-BLOCKING-EVALUATION.conf
  - RESPONSE-950-DATA-LEAKAGES.conf
  - RESPONSE-951-DATA-LEAKAGES-SQL.conf
  - RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  - RESPONSE-953-DATA-LEAKAGES-PHP.conf
  - RESPONSE-954-DATA-LEAKAGES-IIS.conf
  - RESPONSE-955-WEB-SHELLS.conf
  - RESPONSE-959-BLOCKING-EVALUATION.conf
  - RESPONSE-980-CORRELATION.conf
  - /CoreRuleSet/05-exclusions-after-crs.conf