name: simbiat/simbiat-seclang

#This is the default setup that works, this is just https://app.crowdsec.net/hub/author/crowdsecurity/appsec-rules/crs
seclang_rules:
  - SecRuleEngine On
  - SecRequestBodyAccess On
seclang_files_rules:
  - crs-setup.conf
  - REQUEST-901-INITIALIZATION.conf
  - REQUEST-905-COMMON-EXCEPTIONS.conf
  - REQUEST-911-METHOD-ENFORCEMENT.conf
  - REQUEST-913-SCANNER-DETECTION.conf
  - REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  - REQUEST-921-PROTOCOL-ATTACK.conf
  - REQUEST-922-MULTIPART-ATTACK.conf
  - REQUEST-930-APPLICATION-ATTACK-LFI.conf
  - REQUEST-931-APPLICATION-ATTACK-RFI.conf
  - REQUEST-932-APPLICATION-ATTACK-RCE.conf
  - REQUEST-933-APPLICATION-ATTACK-PHP.conf
  - REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  - REQUEST-941-APPLICATION-ATTACK-XSS.conf
  - REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  - REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  - REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  - REQUEST-949-BLOCKING-EVALUATION.conf
  - RESPONSE-950-DATA-LEAKAGES.conf
  - RESPONSE-951-DATA-LEAKAGES-SQL.conf
  - RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  - RESPONSE-953-DATA-LEAKAGES-PHP.conf
  - RESPONSE-954-DATA-LEAKAGES-IIS.conf
  - RESPONSE-955-WEB-SHELLS.conf
  - RESPONSE-959-BLOCKING-EVALUATION.conf
  - RESPONSE-980-CORRELATION.conf

data:
  - source_url: https://hub-data.crowdsec.net/appsec/crs/crs-setup.conf
    dest_file: crs-setup.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-901-INITIALIZATION.conf
    dest_file: REQUEST-901-INITIALIZATION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-905-COMMON-EXCEPTIONS.conf
    dest_file: REQUEST-905-COMMON-EXCEPTIONS.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-911-METHOD-ENFORCEMENT.conf
    dest_file: REQUEST-911-METHOD-ENFORCEMENT.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-913-SCANNER-DETECTION.conf
    dest_file: REQUEST-913-SCANNER-DETECTION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    dest_file: REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-921-PROTOCOL-ATTACK.conf
    dest_file: REQUEST-921-PROTOCOL-ATTACK.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-922-MULTIPART-ATTACK.conf
    dest_file: REQUEST-922-MULTIPART-ATTACK.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-930-APPLICATION-ATTACK-LFI.conf
    dest_file: REQUEST-930-APPLICATION-ATTACK-LFI.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-931-APPLICATION-ATTACK-RFI.conf
    dest_file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-932-APPLICATION-ATTACK-RCE.conf
    dest_file: REQUEST-932-APPLICATION-ATTACK-RCE.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-933-APPLICATION-ATTACK-PHP.conf
    dest_file: REQUEST-933-APPLICATION-ATTACK-PHP.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
    dest_file: REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-941-APPLICATION-ATTACK-XSS.conf
    dest_file: REQUEST-941-APPLICATION-ATTACK-XSS.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    dest_file: REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    dest_file: REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
    dest_file: REQUEST-944-APPLICATION-ATTACK-JAVA.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/REQUEST-949-BLOCKING-EVALUATION.conf
    dest_file: REQUEST-949-BLOCKING-EVALUATION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-950-DATA-LEAKAGES.conf
    dest_file: RESPONSE-950-DATA-LEAKAGES.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-951-DATA-LEAKAGES-SQL.conf
    dest_file: RESPONSE-951-DATA-LEAKAGES-SQL.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    dest_file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-953-DATA-LEAKAGES-PHP.conf
    dest_file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-954-DATA-LEAKAGES-IIS.conf
    dest_file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-955-WEB-SHELLS.conf
    dest_file: RESPONSE-955-WEB-SHELLS.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-959-BLOCKING-EVALUATION.conf
    dest_file: RESPONSE-959-BLOCKING-EVALUATION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/RESPONSE-980-CORRELATION.conf
    dest_file: RESPONSE-980-CORRELATION.conf
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/crawlers-user-agents.data
    dest_file: crawlers-user-agents.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/iis-errors.data
    dest_file: iis-errors.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/java-classes.data
    dest_file: java-classes.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/java-code-leakages.data
    dest_file: java-code-leakages.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/java-errors.data
    dest_file: java-errors.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/lfi-os-files.data
    dest_file: lfi-os-files.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-config-directives.data
    dest_file: php-config-directives.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-errors.data
    dest_file: php-errors.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-errors-pl2.data
    dest_file: php-errors-pl2.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-function-names-933150.data
    dest_file: php-function-names-933150.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-function-names-933151.data
    dest_file: php-function-names-933151.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/php-variables.data
    dest_file: php-variables.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/restricted-files.data
    dest_file: restricted-files.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/restricted-upload.data
    dest_file: restricted-upload.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/scanners-headers.data
    dest_file: scanners-headers.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/scanners-urls.data
    dest_file: scanners-urls.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/scanners-user-agents.data
    dest_file: scanners-user-agents.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/scripting-user-agents.data
    dest_file: scripting-user-agents.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/sql-errors.data
    dest_file: sql-errors.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/ssrf.data
    dest_file: ssrf.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/unix-shell.data
    dest_file: unix-shell.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/web-shells-php.data
    dest_file: web-shells-php.data
    type: modsec
  - source_url: https://hub-data.crowdsec.net/appsec/crs/windows-powershell-commands.data
    dest_file: windows-powershell-commands.data
    type: modsec

# This is the expected setup that is failing
#description: "Rules based on Coraza recommendations with some customizations"
#seclang_files_rules:
#  - 01-coraza-recommended.conf
#  - 02-crs-setup.conf
#  - 03-exclusions-before-crs.conf
#  - /coreruleset/rules/REQUEST-901-INITIALIZATION.conf
#  - /coreruleset/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
#  - /coreruleset/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
#  - /coreruleset/rules/REQUEST-913-SCANNER-DETECTION.conf
#  - /coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
#  - /coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf
#  - /coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf
#  - /coreruleset/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
#  - /coreruleset/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
#  - /coreruleset/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
#  - /coreruleset/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
#  - /coreruleset/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
#  - /coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
#  - /coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
#  - /coreruleset/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
#  - /coreruleset/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
#  - /coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf
#  - /coreruleset/rules/RESPONSE-950-DATA-LEAKAGES.conf
#  - /coreruleset/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
#  - /coreruleset/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
#  - /coreruleset/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
#  - /coreruleset/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
#  - /coreruleset/rules/RESPONSE-955-WEB-SHELLS.conf
#  - /coreruleset/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
#  - /coreruleset/rules/RESPONSE-980-CORRELATION.conf
#  - 04-exclusions-after-crs.conf
#data:
#  - dest_file: /coreruleset/rules/REQUEST-901-INITIALIZATION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-913-SCANNER-DETECTION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-950-DATA-LEAKAGES.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-955-WEB-SHELLS.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/RESPONSE-980-CORRELATION.conf
#    type: modsec
#  - dest_file: /coreruleset/rules/iis-errors.data
#    type: modsec
#  - dest_file: /coreruleset/rules/java-classes.data
#    type: modsec
#  - dest_file: /coreruleset/rules/java-code-leakages.data
#    type: modsec
#  - dest_file: /coreruleset/rules/java-errors.data
#    type: modsec
#  - dest_file: /coreruleset/rules/lfi-os-files.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-config-directives.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-errors.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-errors-pl2.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-function-names-933150.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-function-names-933151.data
#    type: modsec
#  - dest_file: /coreruleset/rules/php-variables.data
#    type: modsec
#  - dest_file: /coreruleset/rules/restricted-files.data
#    type: modsec
#  - dest_file: /coreruleset/rules/restricted-upload.data
#    type: modsec
#  - dest_file: /coreruleset/rules/scanners-user-agents.data
#    type: modsec
#  - dest_file: /coreruleset/rules/sql-errors.data
#    type: modsec
#  - dest_file: /coreruleset/rules/ssrf.data
#    type: modsec
#  - dest_file: /coreruleset/rules/unix-shell.data
#    type: modsec
#  - dest_file: /coreruleset/rules/web-shells-php.data
#    type: modsec
#  - dest_file: /coreruleset/rules/windows-powershell-commands.data
#    type: modsec