name: simbiat/simbiat-seclang
description: "Rules based on Coraza recommendations with some customizations"
seclang_files_rules:
  - /CoreRuleSet/01-coraza-recommended.conf
  - /CoreRuleSet/02-crs-setup.conf
  - /CoreRuleSet/03-custom-blocks.conf
  - /CoreRuleSet/04-exclusions-before-crs.conf
  - REQUEST-901-INITIALIZATION.conf
  - REQUEST-905-COMMON-EXCEPTIONS.conf
  - REQUEST-911-METHOD-ENFORCEMENT.conf
  - REQUEST-913-SCANNER-DETECTION.conf
  - REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  - REQUEST-921-PROTOCOL-ATTACK.conf
  - REQUEST-922-MULTIPART-ATTACK.conf
  - REQUEST-930-APPLICATION-ATTACK-LFI.conf
  - REQUEST-931-APPLICATION-ATTACK-RFI.conf
  - REQUEST-932-APPLICATION-ATTACK-RCE.conf
  - REQUEST-933-APPLICATION-ATTACK-PHP.conf
  - REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  - REQUEST-941-APPLICATION-ATTACK-XSS.conf
  - REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  - REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  - REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  - REQUEST-949-BLOCKING-EVALUATION.conf
  - RESPONSE-950-DATA-LEAKAGES.conf
  - RESPONSE-951-DATA-LEAKAGES-SQL.conf
  - RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  - RESPONSE-953-DATA-LEAKAGES-PHP.conf
  - RESPONSE-954-DATA-LEAKAGES-IIS.conf
  - RESPONSE-955-WEB-SHELLS.conf
  - RESPONSE-959-BLOCKING-EVALUATION.conf
  - RESPONSE-980-CORRELATION.conf
  - /CoreRuleSet/05-exclusions-after-crs.conf
data:
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-901-INITIALIZATION.conf
    dest_file: REQUEST-901-INITIALIZATION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
    dest_file: REQUEST-905-COMMON-EXCEPTIONS.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
    dest_file: REQUEST-911-METHOD-ENFORCEMENT.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-913-SCANNER-DETECTION.conf
    dest_file: REQUEST-913-SCANNER-DETECTION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    dest_file: REQUEST-920-PROTOCOL-ENFORCEMENT.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-921-PROTOCOL-ATTACK.conf
    dest_file: REQUEST-921-PROTOCOL-ATTACK.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-922-MULTIPART-ATTACK.conf
    dest_file: REQUEST-922-MULTIPART-ATTACK.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
    dest_file: REQUEST-930-APPLICATION-ATTACK-LFI.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
    dest_file: REQUEST-931-APPLICATION-ATTACK-RFI.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
    dest_file: REQUEST-932-APPLICATION-ATTACK-RCE.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
    dest_file: REQUEST-933-APPLICATION-ATTACK-PHP.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
    dest_file: REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
    dest_file: REQUEST-941-APPLICATION-ATTACK-XSS.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    dest_file: REQUEST-942-APPLICATION-ATTACK-SQLI.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    dest_file: REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
    dest_file: REQUEST-944-APPLICATION-ATTACK-JAVA.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf
    dest_file: REQUEST-949-BLOCKING-EVALUATION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-950-DATA-LEAKAGES.conf
    dest_file: RESPONSE-950-DATA-LEAKAGES.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
    dest_file: RESPONSE-951-DATA-LEAKAGES-SQL.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    dest_file: RESPONSE-952-DATA-LEAKAGES-JAVA.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
    dest_file: RESPONSE-953-DATA-LEAKAGES-PHP.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
    dest_file: RESPONSE-954-DATA-LEAKAGES-IIS.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-955-WEB-SHELLS.conf
    dest_file: RESPONSE-955-WEB-SHELLS.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
    dest_file: RESPONSE-959-BLOCKING-EVALUATION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/RESPONSE-980-CORRELATION.conf
    dest_file: RESPONSE-980-CORRELATION.conf
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/iis-errors.data
    dest_file: iis-errors.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/java-classes.data
    dest_file: java-classes.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/java-errors.data
    dest_file: java-errors.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/lfi-os-files.data
    dest_file: lfi-os-files.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-config-directives.data
    dest_file: php-config-directives.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-errors.data
    dest_file: php-errors.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-errors-pl2.data
    dest_file: php-errors-pl2.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-function-names-933150.data
    dest_file: php-function-names-933150.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-function-names-933151.data
    dest_file: php-function-names-933151.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/php-variables.data
    dest_file: php-variables.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/restricted-files.data
    dest_file: restricted-files.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/restricted-upload.data
    dest_file: restricted-upload.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/scanners-user-agents.data
    dest_file: scanners-user-agents.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/sql-errors.data
    dest_file: sql-errors.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/ssrf.data
    dest_file: ssrf.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/unix-shell.data
    dest_file: unix-shell.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/web-shells-asp.data
    dest_file: web-shells-asp.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/web-shells-php.data
    dest_file: web-shells-php.data
    type: modsec
  - source_url: https://github.com/coreruleset/coreruleset/raw/refs/tags/v4.14.0/rules/windows-powershell-commands.data
    dest_file: windows-powershell-commands.data
    type: modsec