name: simbiat/simbiat-seclang
description: "Rules based on Coraza recommendations with some customizations"
seclang_files_rules:
  - 01-coraza-recommended.conf
  - 02-crs-setup.conf
  - 03-custom-blocks.conf
  - 04-exclusions-before-crs.conf
  - /coreruleset/rules/REQUEST-901-INITIALIZATION.conf
  - /coreruleset/rules/REQUEST-905-COMMON-EXCEPTIONS.conf
  - /coreruleset/rules/REQUEST-911-METHOD-ENFORCEMENT.conf
  - /coreruleset/rules/REQUEST-913-SCANNER-DETECTION.conf
  - /coreruleset/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
  - /coreruleset/rules/REQUEST-921-PROTOCOL-ATTACK.conf
  - /coreruleset/rules/REQUEST-922-MULTIPART-ATTACK.conf
  - /coreruleset/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf
  - /coreruleset/rules/REQUEST-931-APPLICATION-ATTACK-RFI.conf
  - /coreruleset/rules/REQUEST-932-APPLICATION-ATTACK-RCE.conf
  - /coreruleset/rules/REQUEST-933-APPLICATION-ATTACK-PHP.conf
  - /coreruleset/rules/REQUEST-934-APPLICATION-ATTACK-GENERIC.conf
  - /coreruleset/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
  - /coreruleset/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
  - /coreruleset/rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf
  - /coreruleset/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf
  - /coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf
  - /coreruleset/rules/RESPONSE-950-DATA-LEAKAGES.conf
  - /coreruleset/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf
  - /coreruleset/rules/RESPONSE-952-DATA-LEAKAGES-JAVA.conf
  - /coreruleset/rules/RESPONSE-953-DATA-LEAKAGES-PHP.conf
  - /coreruleset/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf
  - /coreruleset/rules/RESPONSE-955-WEB-SHELLS.conf
  - /coreruleset/rules/RESPONSE-959-BLOCKING-EVALUATION.conf
  - /coreruleset/rules/RESPONSE-980-CORRELATION.conf
  - 05-exclusions-after-crs.conf