[PHP]

; For test environment some functions need to be allowed, so the list is smaller than for PROD
disable_functions = apache_child_terminate,apache_note,apache_setenv,chgrp,debugger_off,debugger_on,define_sys,define_syslog_variables,escapeshellcmd,extract,fsockopen,get_current_user,getmygid,getmyinode,getmypid,getmyuid,ini_restore,leak,listen,mail ,parse_ini_file,passthru,pcntl_alarm,pcntl_async_signals,pcntl_exec,pcntl_get_last_error,pcntl_getpriority,pcntl_setpriority,pcntl_signal,pcntl_signal_dispatch,pcntl_signal_get_handler,pcntl_sigprocmask,pcntl_sigtimedwait,pcntl_sigwaitinfo,pcntl_strerror,pcntl_unshare,pcntl_wait,pcntl_wifcontinued,pcntl_wifexited,pcntl_wifstopped,pcntl_wstopsig,pfsockopen,phpinfo,popen,posix,posix_ctermid,posix_getcwd,posix_getegid,posix_geteuid,posix_getgid,posix_getgrgid,posix_getgrnam,posix_getgroups,posix_getlogin,posix_getpgid,posix_getpgrp,posix_getpid,posix_getpwnam,posix_getpwuid,posix_getrlimit,posix_getsid,posix_isatty,posix_mkfifo,posix_setegid,posix_seteuid,posix_setgid,posix_setpgid,posix_setsid,posix_setuid,posix_times,posix_ttyname,posix_uname,proc_nice,show_source,system


; Allow some extra data in exceptions on test environment
zend.exception_ignore_args = off
zend.exception_string_param_max_len = 15

; Report all on test environment and display errors
error_reporting = E_ALL
display_errors = On
display_startup_errors = On


[mysqlnd]
; Allow collection of memory usage statistics
mysqlnd.collect_memory_statistics = On


[Assertion]
; Compile Zend assertions on test
zend.assertions = 1

[opcache]
; Disable JIT, since using xDebug
opcache.jit = disable
; Revalidate opcache fore frequently
opcache.revalidate_freq = 2

[xdebug]
xdebug.mode = develop,debug,coverage
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.var_display_max_children = -1
xdebug.var_display_max_data = -1
xdebug.var_display_max_depth = -1
;extension = pcntl