filenames:
  - /usr/local/logs/access.log
labels:
  type: caddy
---
filenames:
  - /usr/local/logs/mariadb.log
labels:
  type: mariadb
---
filenames:
  - /var/log/auth.log
  - /var/log/syslog
labels:
  type: syslog