CREATE TABLE `ffxiv__character` (
  `characterid` int(10) unsigned NOT NULL COMMENT 'Character ID taken from Lodestone URL (https://eu.finalfantasyxiv.com/lodestone/character/characterid/)',
  `userid` int(10) unsigned DEFAULT NULL COMMENT 'ID of the user, that is linked to the character',
  `serverid` tinyint(2) unsigned DEFAULT NULL COMMENT 'ID of the server character resides on',
  `name` varchar(50) NOT NULL COMMENT 'Character''s name',
  `manual` tinyint(1) unsigned NOT NULL DEFAULT 0 COMMENT 'Flag indicating whether entity was added manually',
  `avatar` varchar(66) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_nopad_as_ci NOT NULL COMMENT 'ID portion of the link to character avatar (requires adding of ''l0_640x873.jpg'' or ''c0_96x96.jpg'' to the end of the field and ''https://img2.finalfantasyxiv.com/f/'' to the beginning to be turned into actual image link)',
  `registered` date NOT NULL DEFAULT current_timestamp() COMMENT 'When character was initially added to tracker',
  `updated` datetime(6) NOT NULL DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6) COMMENT 'When character was last updated on the tracker',
  `deleted` date DEFAULT NULL COMMENT 'Date when character was marked as deleted',
  `enemyid` int(10) unsigned DEFAULT NULL COMMENT 'ID of an enemy that "killed" the character',
  `biography` text CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_nopad_ai_ci DEFAULT NULL COMMENT 'Text from "Character profile" section on Lodestone',
  `titleid` smallint(5) unsigned DEFAULT NULL COMMENT 'ID of achievement title currently being used by character',
  `clanid` tinyint(2) unsigned DEFAULT NULL COMMENT 'Clan ID identifying both clan and race of the character',
  `genderid` tinyint(1) unsigned NOT NULL DEFAULT 1 COMMENT '0 for female and 1 for male',
  `namedayid` smallint(3) unsigned NOT NULL DEFAULT 1 COMMENT 'ID of nameday (birthday) of character',
  `guardianid` tinyint(2) unsigned NOT NULL DEFAULT 4 COMMENT 'ID of Guardian chosen by character',
  `cityid` tinyint(1) unsigned NOT NULL DEFAULT 5 COMMENT 'ID of character''s starting city',
  `gcrankid` tinyint(2) unsigned DEFAULT NULL COMMENT 'ID of character''s Grand Company''s affiliation and current rank there',
  `pvp_matches` int(10) DEFAULT 0 COMMENT 'Number of PvP matches character participated in',
  `Alchemist` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Alchemist job',
  `Armorer` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Armorer job',
  `Astrologian` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Astrologian job',
  `Bard` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Bard job',
  `BlackMage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Black Mage job',
  `Blacksmith` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Blacksmith job',
  `BlueMage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Blue Mage job',
  `Botanist` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Botanist job',
  `Carpenter` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Carpenter job',
  `Culinarian` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Culinarian job',
  `Dancer` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Dancer job',
  `DarkKnight` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Dark Knight job',
  `Dragoon` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Dragoon job',
  `Fisher` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Fisher job',
  `Goldsmith` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Goldsmith job',
  `Gunbreaker` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Gunbreaker job',
  `Leatherworker` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Leatherworker job',
  `Machinist` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Machinist job',
  `Miner` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Miner job',
  `Monk` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Monk job',
  `Ninja` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Ninja job',
  `Paladin` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Paladin job',
  `Pictomancer` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Pictomancer job',
  `Reaper` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Reaper job',
  `RedMage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Red Mage job',
  `Sage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Sage job',
  `Samurai` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Samurai job',
  `Scholar` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Scholar job',
  `Summoner` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Summoner job',
  `Viper` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Viper job',
  `Warrior` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Warrior job',
  `Weaver` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of Weaver job',
  `WhiteMage` tinyint(3) unsigned NOT NULL DEFAULT 0 COMMENT 'Level of White Mage job',
  PRIMARY KEY (`characterid`) USING BTREE,
  KEY `clanid` (`clanid`),
  KEY `guardianid` (`guardianid`),
  KEY `namedayid` (`namedayid`),
  KEY `cityid` (`cityid`),
  KEY `serverid` (`serverid`),
  KEY `gcrankid` (`gcrankid`),
  KEY `titleid` (`titleid`),
  KEY `registered` (`registered`),
  KEY `deleted` (`deleted`),
  KEY `name_order` (`name`),
  KEY `enemyid` (`enemyid`),
  KEY `updated` (`updated` DESC),
  KEY `userid` (`userid`),
  FULLTEXT KEY `name` (`name`),
  FULLTEXT KEY `biography` (`biography`),
  CONSTRAINT `cityid` FOREIGN KEY (`cityid`) REFERENCES `ffxiv__city` (`cityid`) ON UPDATE CASCADE,
  CONSTRAINT `clanid` FOREIGN KEY (`clanid`) REFERENCES `ffxiv__clan` (`clanid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `enemyid` FOREIGN KEY (`enemyid`) REFERENCES `ffxiv__enemy` (`enemyid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `gcrankid` FOREIGN KEY (`gcrankid`) REFERENCES `ffxiv__grandcompany_rank` (`gcrankid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `guardianid` FOREIGN KEY (`guardianid`) REFERENCES `ffxiv__guardian` (`guardianid`) ON UPDATE CASCADE,
  CONSTRAINT `namedayid` FOREIGN KEY (`namedayid`) REFERENCES `ffxiv__nameday` (`namedayid`) ON UPDATE CASCADE,
  CONSTRAINT `serverid` FOREIGN KEY (`serverid`) REFERENCES `ffxiv__server` (`serverid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `titleid` FOREIGN KEY (`titleid`) REFERENCES `ffxiv__achievement` (`achievementid`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `userid` FOREIGN KEY (`userid`) REFERENCES `uc__users` (`userid`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_nopad_as_cs ROW_FORMAT=DYNAMIC COMMENT='Characters found on Lodestone' `PAGE_COMPRESSED`='ON';